### ISSUE TITLE
Add chat feature

### ISSUE THREAD

**Issue by vrajdesai78** [Huddle01/Audio-spaces-example-app#6]
## Objective
Implement a chat feature using the [`sendData`](https://docs.huddle01.com/docs/React/hooks/useAppUtils) method from our SDK, integrating it with a suitable user interface.

## Picking up this issue
If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you.

## Questions
- If you need assistance or clarification, feel free to comment below.
- You can also ask your doubts 24x7 in our [Discord channel](https://discord.com/invite/huddle01-890224574761926756).
- Check your ranking after finishing this task on the [Leaderboard](https://huddle01.notion.site/Huddle01-Hacktoberfest-Leaderboard-34c909db00eb4828aab3f1da8502a6fa?pvs=4).

## Resources
- Familiarize yourself with the [`sendData`](https://docs.huddle01.com/docs/React/hooks/useAppUtils) method and its usage. 
- You can listen to `room:data-received` event to get the data sent from `sendData`. 

**Good Luck! 🍀**

**Comment by vrajdesai78** [comment]
> picking this up

Hey @xinkin I have assigned this issue to you, feel free to ask any questions you have.

**Comment by lazyMonk1010** [comment]
Hey @vrajdesai78 I want to work on this issue!

**Comment by vrajdesai78** [comment]
> Hey @vrajdesai78 I want to work on this issue!

Sorry @lazyMonk1010, but I can't assign you this issue as it's already assign to @xinkin, but you can pick up another available issues. Thanks
