### ISSUE TITLE
Add option to change media device 

### ISSUE THREAD

**Issue by vrajdesai78** [Huddle01/Audio-spaces-example-app#7]
## Objective
Create a settings modal within the application that allows users to change their active media devices, such as speakers and microphones.

## Picking up this issue
If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you.

## Questions
- If you need assistance or clarification, feel free to comment below.
- You can also ask your doubts 24x7 in our [Discord channel](https://discord.com/invite/huddle01-890224574761926756).
- Check your ranking after finishing this task on the [Leaderboard](https://huddle01.notion.site/Huddle01-Hacktoberfest-Leaderboard-34c909db00eb4828aab3f1da8502a6fa?pvs=4).

## Resources
- You can check `enumerateDevices()` from `useAudio()` [hook](https://huddle01.com/docs/React/hooks/useAudio) to get list of audio input devices and for audio output devices, you can check [here](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices). 

**Good Luck! 🍀**

**Comment by KoxyG** [comment]
picking this up

**Comment by lazyMonk1010** [comment]
- hey @vrajdesai78 I want to work on this issue, do assign me this 
- picking this up!

**Comment by vrajdesai78** [comment]
> picking this up

Hey @KoxyG, thanks for picking up this issue. If you have any questions feel free to drop it here.

**Comment by vrajdesai78** [comment]
> * hey @vrajdesai78 I want to work on this issue, do assign me this
> * picking this up!

Hey, as of now I can't assign you this issue as @KoxyG already commented before you. So, I would recommend you to look at other available issues. Thanks

**Comment by neel-ds** [comment]
Hey @vrajdesai78, I have completed this issue in PR #11. Please check it out and assign me.

**Comment by scarlettverse** [comment]
Hi @neel-ds ,

Are you in the Huddle01 Discord? That would make it easiest to provide you with your Hacktoberfest winnings 😄

**Comment by neel-ds** [comment]
Yes! Let me ping you there
